---
abstract: 'Creating port from perl module'
author:
  - 'Andrey Kostenko <andrey@kostenko.name>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Pm2Port
no_index:
  directory:
    - inc
    - t
requires:
  CPANPLUS: 0
  ExtUtils::MakeMaker: 0
  File::Temp: 0
  FreeBSD::Ports::INDEXhash: 0
  Getopt::Long: 0
  JSON::XS: 0
  Term::ReadLine: 0
  YAML: 0
  perl: 5.10.0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://developers.rambler.ru/svn/perlmodules/App-Pm2Port
version: 0.27
