#!/usr/bin/env perl

use strict;
use warnings;

use App::Pm2Port;

( bless {}, __PACKAGE__ )->main();

sub main {
    my $self = shift;
    my $opts = {};
    die "Usage: $0 Module::Name" unless @ARGV;
    my $result = GetOptions(
        'h|help' => sub {
            print
              qq{Usage: $0 [ --module=My::Module ] [ --info ] [ --no-tests ] [ --no-upload ] [ --no-commit ] [ --cpan ]\n};
            exit 0;
        },
        'info'      => \$opts->{'info_only'},
        'no-tests'  => \$opts->{'notest'},
        'no-upload' => \$opts->{'no_upload'},
        'no-commit' => \$opts->{'no_commit'},
        'freebsd'   => \$opts->{'submit_to_freebsd'},
        'modules=s' => \$opts->{'module'},
    );
    my $a = App::Pm2Port->new($opts);

    $a->run;
}

=head1 NAME

pm2port - Creates FreeBSD port from Perl module

=head1 SYNOPSYS

    cd port-directory
    pm2port Variable::Eject

=head1 LICENSE

This module is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=head1 AUTHOR

Andrey Kostenko E<lt>andrey@kostenko.nameE<gt>

=cut
